#!/usr/bin/perl
use Switch;
use FTN::Packet;

#Turn off autobuffering
local $| = 1;

#Version information
my $version = " .01-alpha";
my $ver_short = "Perl Packet Inspector : TBX Software : bbs.thebytexchange.com:23\nVersion:" . $version . "\n\n";

print $ver_short;


print "DO NOT USE THIS APLHA VERSION... IT IS UNTESTED...\n";
print "PAUSING FOR 10 SECONDS FOR YOU TO THINK ABOUT IT...\n";
print "HIT CTL-C TO QUIT\n";


for (my $i = 0; $i <= 10; $i++) {
	printf("#");
	sleep 1;
}

print "\n";




check_arguments();


sub check_arguments {
	switch ($ARGV[0]) {
	 	case "-v"       {view_packet()}
		case "-h"       {print_help()}
		case "-ver"     {print_version()}
		case "-hver"    {print_version(); print_help();}
		case ""         {print "Error 100: No argument(s) specified, exiting.\n -h for help information.\n"; exit}
		case "-install" {install_dependencies()}
		case "-errors"  {print error_list()}
		else		{print "Error 101: Invalid argument(s) specificed.\n-h for help information.\n"}
	}
}

sub check_pktfile {

}



#Print help file

sub print_help {
print "Packet Inspector Help File\n";
print "Syntax expected:  inspkt -[arguments] /path/to/packet/packet.pkt\n\n";
print "Available Arguments:\n";
print "-argument        Description\n";
print "================================================================\n";
print "-v               View Packet Information\n";
print "-h               This help file\n";
print "-ver             Perl Packet Inspector version information\n";
print "\n\n";

return 0;

}

sub print_version {
print "Version Information:\n";
print "======================\n";
print "inspkt - Perl Packet Inspector\n";
print "Version: $ver_short\n";
print "Written by TBX Software - The ByteXchange BBS\n";
print "Author: Chad Adams (nugax)\n";
print "Help? Fidonet: chad adams@1:130/210\n";
print "E-mail: cadams\@thebytexchange.com\n";
print "BBS: Telnet @ bbs.thebytexchange.com port 23";
print "\n\n";

return 0;
}

sub error_list {
print "inspkt Error List\n";
print "=========================\n\n";
print "error 100  - No argument specified on command line - none\n";
print "error 101  - Invalid argument specified on command line\n";
print "error 104  - No filename specified for packet for use with -v\n";
print "error 120  - Invalid option (y/n) selected. Must select either Y or N\n";
return 0;
}


sub view_packet {

#Check for filename give
if ($ARGV[1] eq "") {
 	print "Error 104: No packet filename specificed.\n";
	return 0;
	}

#Check to ensure file exists - that was give for filename for packet

my $filename = $ARGV[1];

print "Reading packet: " . $filename . "...\n";

$messages = FTN::Packet::read_ftn_packet($filename);

for $i ( 0 .. $#{$messages} ) {


        $msg_area = ${$messages}[i]{area};
        $msg_date = ${$messages}[i]{ftscdate};
        $msg_tonode = ${$messages}[i]{tonode};
        $msg_from = ${$messages}[i]{from};
        $msg_to = ${$messages}[i]{to};
        $msg_subj = ${$messages}[i]{subj};
        $msg_msgid = ${$messages}[i]{msgid};
        $msg_replyid = ${$messages}[i]{replyid};
        $msg_body = ${$messages}[i]{body};
        $msg_ctrl = ${$messages}[i]{ctrlinfo};


	#Print packet contents
	print "\n";
	print "==================================================================\n";
	print " Packet $filename contents\n";
	print "==================================================================\n\n";
	print "Message Area: " . $msg_area . "\n";
	print "Message Date: " . $msg_date . "\n";
	print "To Node: " . $msg_tonode . "\n";
	print "Message From: " . $msg_from . "\n";
	print "Message To: " . $msg_to . "\n";
	print "Subject: " . $msg_subj . "\n";
	print "MSG ID: " . $msg_msgid . "\n";
	print "Reply ID: " . $msg_replyid . "\n\n";
	print "          Kludge Line(s):\n ";
	print "  ---------------------------------\n\n";
	print $msg_ctrl . "\n\n";

	print "Do you want to view the message? (y/n) ";

	my $answer = <STDIN>;
	$answer = uc($answer);
	chomp($answer);

	if ($answer eq "Y") {
		print "\n\n";
		print "           Message Body:\n";
		print "  ---------------------------------\n\n";


	        print $msg_body;

	        print "\n\n\n";
       	        print "Press any key to exit...";
	        <STDIN>;
		return 0;
	}

	if ($answer eq "N") {
		exit;
        }

	else {
	print "\nError 120: Unexpected entry.\n";}
	return 0;

	}

}
